pipeline {
    agent any
    stages {
        stage('Build Backend') {
            steps {
                sh 'docker build -t devops-backend -f docker/Dockerfile.backend .'
            }
        }
        stage('Build Frontend') {
            steps {
                sh 'docker build -t devops-frontend -f docker/Dockerfile.frontend .'
            }
        }
        stage('Test Backend') {
            steps {
                sh 'pytest backend/tests/'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml up -d'
            }
        }
    }
}

